version: "3.5"

services:
  ct:
    image: quay.io/coreos/ct:v0.9.0@sha256:06ada07307862e22809e652efb04953a8f8b1827663fe947c3a751d4e144c611
    volumes:
      - type: bind
        source: .
        target: /host
        read_only: true
