version: "3.4"

services:
  snmp-exporter:
    restart: always
    image: prom/snmp-exporter:v0.17.0@sha256:ca4a65162cb746802cf7906548098407df7a925a2374f36d58d19e9321695895
    read_only: yes
    volumes:
      - type: bind
        source: ./snmp-exporter/snmp.yml
        target: /etc/snmp_exporter/snmp.yml
        read_only: true
    networks:
      - prometheus-exporters
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:snmp.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=9116"
  blackbox-exporter:
    restart: always
    image: prom/blackbox-exporter:v0.16.0@sha256:86acd01eece9da3e4f1eedbd7ddb58a304740aa9426632e5de5c1d07dd7b749a
    read_only: yes
    volumes:
      - type: bind
        source: ./blackbox-exporter/config.yml
        target: /etc/blackbox_exporter/config.yml
        read_only: true
    networks:
      - prometheus-exporters
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:blackbox.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=9115"
  prometheus:
    restart: always
    image: prom/prometheus:v2.16.0@sha256:efd99a6be65885c07c559679a0df4ec709604bcdd8cd83f0d00a1a683b28fb6a
    read_only: yes
    command:
      # The following options are from https://github.com/prometheus/prometheus/blob/master/Dockerfile
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # The following options are our own
      - "--storage.tsdb.retention.size=60GB"
    volumes:
      - type: bind
        source: "${PROMETHEUS_CONFIG:-./prometheus/prometheus.yml}"
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: bind
        source: "${PROMETHEUS_PING:-./prometheus/ping.json}"
        target: /etc/prometheus/ping.json
        read_only: true
      - type: volume
        source: prometheus
        target: /prometheus
    networks:
      - prometheus-exporters
      - prometheus-frontend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:prometheus.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=9090"
  grafana:
    restart: always
    image: grafana/grafana:6.7.4@sha256:43340812d14aa3e60810b85ee9caaf0e423e7aad01000b704cd8ddfb2bb1248e
    read_only: yes
    tmpfs:
      - /tmp
    volumes:
      - type: volume
        source: grafana
        target: /var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-polystat-panel"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=3000"
    networks:
      - prometheus-frontend
      - traefik
  traefik:
    restart: always
    image: traefik:1.7.26-alpine@sha256:3cbe9e62ef26a9ac17b25702754dfbf56dd346850170be90eabd370f24190ef1
    read_only: yes
    command: --api --docker --docker.exposedbydefault=false
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./traefik.toml
        target: /traefik.toml
      - type: bind
        source: ../prometheus-westnetz-acme.json
        target: /acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=8080"
    networks:
      - traefik

networks:
  prometheus-exporters:
  prometheus-frontend:
  traefik:
    external: true

volumes:
  grafana:
  prometheus:
