version: "3.4"

services:
  snmp-exporter:
    image: prom/snmp-exporter:v0.15.0@sha256:dd340b95d0749c5af15a15601ba57d4169084263ea34d7c642dd72357705eba1
    read_only: yes
    volumes:
      - type: bind
        source: ./snmp-exporter/snmp.yml
        target: /etc/snmp_exporter/snmp.yml
        read_only: true
    networks:
      - prometheus-exporters
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.14.0@sha256:c20445e0cc628fa4b227fe2f694c22a314beb43fd8297095b6ee6cbc67161336
    read_only: yes
    volumes:
      - type: bind
        source: ./blackbox-exporter/config.yml
        target: /etc/blackbox_exporter/config.yml
        read_only: true
    networks:
      - prometheus-exporters
  prometheus:
    image: prom/prometheus:v2.8.1@sha256:7ebbdf175da46fa346ba1e24cf0299bf47c31d199ffc276df1c68ed323606c31
    read_only: yes
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
        read_only: true
      - type: volume
        source: prometheus
        target: /prometheus
    networks:
      - prometheus-exporters
      - prometheus-frontend
  grafana:
    image: grafana/grafana:6.1.3@sha256:8fad1cc242f9a6b61fa8ee28956022a89ca3d687f6733e7b1407ba513be174d5
    read_only: yes
    volumes:
      - type: volume
        source: grafana
        target: /var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-polystat-panel"
    networks:
      - prometheus-frontend
      - traefik
  traefik:
    image: traefik:1.7-alpine@sha256:0531581bde9da0670fc2c7a4e419e1cc38abff74e7ba06410bf2b1b55c70ef15
    read_only: yes
    command: --api --docker --docker.exposedbydefault=false
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./traefik.toml
        target: /traefik.toml
      - type: bind
        source: ./acme.json
        target: /acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=8080"
    networks:
      - traefik

networks:
  prometheus-exporters:
  prometheus-frontend:
  traefik:
    external: true

volumes:
  grafana:
  prometheus:
