version: "3.4"

services:
  snmp-exporter:
    restart: always
    image: prom/snmp-exporter:v0.16.1@sha256:e28c907b3df681851f41fea19ac51c649da518232c7aeb58872283fc837e1fcb
    read_only: yes
    volumes:
      - type: bind
        source: ./snmp-exporter/snmp.yml
        target: /etc/snmp_exporter/snmp.yml
        read_only: true
    networks:
      - prometheus-exporters
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:snmp.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=9116"
  blackbox-exporter:
    restart: always
    image: prom/blackbox-exporter:v0.16.0@sha256:86acd01eece9da3e4f1eedbd7ddb58a304740aa9426632e5de5c1d07dd7b749a
    read_only: yes
    volumes:
      - type: bind
        source: ./blackbox-exporter/config.yml
        target: /etc/blackbox_exporter/config.yml
        read_only: true
    networks:
      - prometheus-exporters
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:blackbox.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=9115"
  prometheus:
    restart: always
    image: prom/prometheus:v2.14.0@sha256:3d53ce329b25cc0c1bfc4c03be0496022d81335942e9e0518ded6d50a5e6c638
    read_only: yes
    command:
      # The following options are from https://github.com/prometheus/prometheus/blob/master/Dockerfile
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # The following options are our own
      - "--storage.tsdb.retention.size=60GB"
    volumes:
      - type: bind
        source: "${PROMETHEUS_CONFIG:-./prometheus/prometheus.yml}"
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: bind
        source: "${PROMETHEUS_PING:-./prometheus/ping.json}"
        target: /etc/prometheus/ping.json
        read_only: true
      - type: volume
        source: prometheus
        target: /prometheus
    networks:
      - prometheus-exporters
      - prometheus-frontend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:prometheus.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=9090"
  grafana:
    restart: always
    image: grafana/grafana:6.5.1@sha256:98352c51c952d749e74899302eaffea749423ee379548a4d3fb829a74291783d
    read_only: yes
    tmpfs:
      - /tmp
    volumes:
      - type: volume
        source: grafana
        target: /var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-polystat-panel"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=3000"
    networks:
      - prometheus-frontend
      - traefik
  traefik:
    restart: always
    image: traefik:v1.7.20-alpine@sha256:ce4f1f9ec3de9c802a1d6020928358d7301452fc5c009ea314fbaa728e69aa3d
    read_only: yes
    command: --api --docker --docker.exposedbydefault=false
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./traefik.toml
        target: /traefik.toml
      - type: bind
        source: ../prometheus-westnetz-acme.json
        target: /acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH_BASIC}"
      - "traefik.docker.network=traefik"
      - "traefik.port=8080"
    networks:
      - traefik

networks:
  prometheus-exporters:
  prometheus-frontend:
  traefik:
    external: true

volumes:
  grafana:
  prometheus:
