version: "3.4"

services:
  snmp-exporter:
    image: prom/snmp-exporter:v0.15.0@sha256:dd340b95d0749c5af15a15601ba57d4169084263ea34d7c642dd72357705eba1
    read_only: yes
    volumes:
      - type: bind
        source: ./snmp-exporter/snmp.yml
        target: /etc/snmp_exporter/snmp.yml
        read_only: true
    networks:
      - prometheus-exporters
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.14.0@sha256:c20445e0cc628fa4b227fe2f694c22a314beb43fd8297095b6ee6cbc67161336
    read_only: yes
    volumes:
      - type: bind
        source: ./blackbox-exporter/config.yml
        target: /etc/blackbox_exporter/config.yml
        read_only: true
    networks:
      - prometheus-exporters
  prometheus:
    image: prom/prometheus:v2.8.1@sha256:7ebbdf175da46fa346ba1e24cf0299bf47c31d199ffc276df1c68ed323606c31
    read_only: yes
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
        read_only: true
      - type: volume
        source: prometheus
        target: /prometheus
    networks:
      - prometheus-exporters
      - prometheus-frontend

networks:
  prometheus-exporters:
  prometheus-frontend:

volumes:
  prometheus:
